/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rpn.calc;

import java.io.Console;
import java.util.Stack;

public class App {

    public static void main(String[] args) {

        Console console = System.console();
        console.writer().write("Starting RPN Calculator...\nType 'exit' to terminate.\nUse the following commands: " +
                "sqrt + - * / undo clear.\nUse integers or floating points.\n");
        console.flush();

        Calculator calc = new RpnCalculator(new Stack<>(), new Stack<>(), new OperandFactory(), CalculatorUtils.provideDecimalFormat());

        while (true) {
            String input = console.readLine();
            if (input.equals("exit")) {
                break;
            }
            String result = calc.submit(input);
            console.writer().write(result + "\n");
            console.flush();
        }
    }
}

